import { runDatabaseOperation } from "@/database/database";
import { DoseStatus } from "@/features/doses/dose.types";

export type ReminderOccurrence = { id: string; profileId: string; medicationId: string; scheduleId: string; scheduledDate: string; scheduledTime: string; nativeNotificationId?: string; status: "scheduled" | "cancelled" | "cleanup_failed"; };
type Row = { id: string; profile_id: string; medication_id: string; schedule_id: string; scheduled_date: string; scheduled_time: string; native_notification_id: string | null; status: ReminderOccurrence["status"]; };
const map = (row: Row): ReminderOccurrence => ({ id: row.id, profileId: row.profile_id, medicationId: row.medication_id, scheduleId: row.schedule_id, scheduledDate: row.scheduled_date, scheduledTime: row.scheduled_time, nativeNotificationId: row.native_notification_id ?? undefined, status: row.status });
const id = () => `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;

export async function saveReminderOccurrence(input: Omit<ReminderOccurrence, "id" | "status">): Promise<void> { const now = new Date().toISOString(); await runDatabaseOperation(async (db) => { await db.runAsync(`INSERT INTO scheduled_reminder_occurrences (id, profile_id, medication_id, schedule_id, scheduled_date, scheduled_time, native_notification_id, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'scheduled', ?, ?) ON CONFLICT(schedule_id, scheduled_date, scheduled_time) DO UPDATE SET profile_id=excluded.profile_id, medication_id=excluded.medication_id, native_notification_id=excluded.native_notification_id, status='scheduled', updated_at=excluded.updated_at`, [id(), input.profileId, input.medicationId, input.scheduleId, input.scheduledDate, input.scheduledTime, input.nativeNotificationId ?? null, now, now]); }); }
export async function getReminderOccurrence(profileId: string, scheduleId: string, date: string, time: string): Promise<ReminderOccurrence | null> { return runDatabaseOperation(async (db) => { const row = await db.getFirstAsync<Row>(`SELECT * FROM scheduled_reminder_occurrences WHERE profile_id=? AND schedule_id=? AND scheduled_date=? AND scheduled_time=?`, [profileId, scheduleId, date, time]); return row ? map(row) : null; }); }
export async function markReminderOccurrence(profileId: string, scheduleId: string, date: string, time: string, status: ReminderOccurrence["status"]): Promise<void> { await runDatabaseOperation(async (db) => { await db.runAsync(`UPDATE scheduled_reminder_occurrences SET status=?, updated_at=? WHERE profile_id=? AND schedule_id=? AND scheduled_date=? AND scheduled_time=?`, [status, new Date().toISOString(), profileId, scheduleId, date, time]); }); }
export async function markScheduleOccurrencesCancelled(scheduleId: string): Promise<void> { await runDatabaseOperation(async (db) => { await db.runAsync(`UPDATE scheduled_reminder_occurrences SET status='cancelled', updated_at=? WHERE schedule_id=? AND status='scheduled'`, [new Date().toISOString(), scheduleId]); }); }
export async function getDoseOccurrenceReminderStatus(profileId: string, scheduleId: string, date: string, time: string): Promise<{ status: DoseStatus; statusRecordedAt?: string } | null> { return runDatabaseOperation(async (db) => { const row = await db.getFirstAsync<{ status: DoseStatus; status_recorded_at: string | null }>(`SELECT status, status_recorded_at FROM dose_records WHERE profile_id=? AND schedule_id=? AND scheduled_date=? AND scheduled_time=?`, [profileId, scheduleId, date, time]); return row ? { status: row.status, statusRecordedAt: row.status_recorded_at ?? undefined } : null; }); }
export async function hasScheduledReminderOccurrences(profileId: string, scheduleId: string): Promise<boolean> { return runDatabaseOperation(async (db) => { const row = await db.getFirstAsync<{ total: number }>(`SELECT COUNT(*) AS total FROM scheduled_reminder_occurrences WHERE profile_id=? AND schedule_id=? AND status='scheduled'`, [profileId, scheduleId]); return (row?.total ?? 0) > 0; }); }
