import { runDatabaseOperation, runExclusiveDatabaseTransaction } from "@/database/database";
import { CreateDoseOccurrenceInput, DoseRecord, DoseStatus, TodayDose } from "./dose.types";
import { isDoseStatusTransitionAllowed } from "./dose.domain";

type DoseRow = { id: string; profile_id: string; medication_id: string; schedule_id: string; scheduled_date: string; scheduled_time: string; scheduled_at: string; status: DoseStatus; taken_at: string | null; notes: string | null; medication_name: string | null; medication_dosage: string | null; created_at: string; updated_at: string; };
type TodayDoseRow = DoseRow & { medication_name: string; medication_dosage: string; };
const newId = () => `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
function map(row: DoseRow): DoseRecord { return { id: row.id, profileId: row.profile_id, medicationId: row.medication_id, scheduleId: row.schedule_id, scheduledDate: row.scheduled_date, scheduledTime: row.scheduled_time, scheduledAt: row.scheduled_at, status: row.status, takenAt: row.taken_at ?? undefined, notes: row.notes ?? undefined, medicationName: row.medication_name ?? undefined, medicationDosage: row.medication_dosage ?? undefined, createdAt: row.created_at, updatedAt: row.updated_at }; }
function requireProfile(profileId: string): void { if (!profileId.trim()) throw new Error("Choose a profile before recording doses."); }

export async function createDoseOccurrences(occurrences: CreateDoseOccurrenceInput[]): Promise<void> { if (!occurrences.length) return; await runExclusiveDatabaseTransaction(async (db) => { for (const item of occurrences) { requireProfile(item.profileId); const now = new Date().toISOString(); await db.runAsync(`INSERT OR IGNORE INTO dose_records (id, profile_id, medication_id, schedule_id, scheduled_date, scheduled_time, scheduled_at, status, medication_name, medication_dosage, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, [newId(), item.profileId, item.medicationId, item.scheduleId, item.scheduledDate, item.scheduledTime, `${item.scheduledDate}T${item.scheduledTime}:00`, "pending", item.medicationName, item.medicationDosage, now, now]); } }); }
export async function getTodayDosesByDate(profileId: string, date: string): Promise<TodayDose[]> { requireProfile(profileId); return runDatabaseOperation(async (db) => (await db.getAllAsync<TodayDoseRow>(`SELECT dose_records.*, COALESCE(dose_records.medication_name, medications.name, 'Medication unavailable') AS medication_name, COALESCE(dose_records.medication_dosage, medications.dosage, '') AS medication_dosage FROM dose_records LEFT JOIN medications ON medications.id = dose_records.medication_id WHERE dose_records.profile_id = ? AND dose_records.scheduled_date = ? ORDER BY dose_records.scheduled_time ASC, medication_name COLLATE NOCASE ASC`, [profileId, date])).map((row) => ({ ...map(row), medicationName: row.medication_name, medicationDosage: row.medication_dosage }))); }
export async function getDoseById(profileId: string, id: string): Promise<DoseRecord | null> { requireProfile(profileId); return runDatabaseOperation(async (db) => { const row = await db.getFirstAsync<DoseRow>(`SELECT * FROM dose_records WHERE id=? AND profile_id=?`, [id, profileId]); return row ? map(row) : null; }); }
export async function getPendingDosesByDate(profileId: string, date: string): Promise<DoseRecord[]> { requireProfile(profileId); return runDatabaseOperation(async (db) => (await db.getAllAsync<DoseRow>(`SELECT * FROM dose_records WHERE profile_id=? AND scheduled_date=? AND status='pending' ORDER BY scheduled_time ASC`, [profileId, date])).map(map)); }
export async function deletePendingDosesForScheduleFromDate(scheduleId: string, fromDate: string): Promise<void> { await runDatabaseOperation(async (db) => { await db.runAsync(`DELETE FROM dose_records WHERE schedule_id=? AND scheduled_date>=? AND status='pending'`, [scheduleId, fromDate]); }); }
async function update(profileId: string, id: string, status: Extract<DoseStatus, "taken" | "skipped" | "missed">, takenAt?: string): Promise<void> { requireProfile(profileId); await runExclusiveDatabaseTransaction(async (db) => { const dose = await db.getFirstAsync<Pick<DoseRow, "status">>(`SELECT status FROM dose_records WHERE id=? AND profile_id=?`, [id, profileId]); if (!dose) throw new Error("Dose record not found."); if (!isDoseStatusTransitionAllowed(dose.status, status)) throw new Error("This dose has already been recorded."); const result = await db.runAsync(`UPDATE dose_records SET status=?, taken_at=?, updated_at=? WHERE id=? AND profile_id=? AND status='pending'`, [status, takenAt ?? null, new Date().toISOString(), id, profileId]); if (result.changes !== 1) throw new Error("This dose was changed before it could be saved. Refresh and try again."); }); }
export const markDoseTakenInDatabase = (profileId: string, id: string, takenAt: string) => update(profileId, id, "taken", takenAt);
export const markDoseSkippedInDatabase = (profileId: string, id: string) => update(profileId, id, "skipped");
export const markDoseMissedInDatabase = (profileId: string, id: string) => update(profileId, id, "missed");
