import { runDatabaseOperation, runExclusiveDatabaseTransaction } from "@/database/database";
import type { SQLiteDatabase } from "expo-sqlite";
import { calculateTakenInventoryConsumption } from "@/features/refills/refill.domain";
import { CreateDoseOccurrenceInput, DoseRecord, DoseStatus, TodayDose } from "./dose.types";
import { assertDoseCanBeRecordedOnLocalDate, isDoseStatusTransitionAllowed } from "./dose.domain";
import { canCorrectDoseStatus, DoseStatusCorrectionTarget, getReversedInventoryQuantity } from "./dose-status-correction.domain";

type DoseRow = { id: string; profile_id: string; medication_id: string; schedule_id: string; scheduled_date: string; scheduled_time: string; scheduled_at: string; status: DoseStatus; taken_at: string | null; status_recorded_at: string | null; notes: string | null; medication_name: string | null; medication_dosage: string | null; created_at: string; updated_at: string; };
type TodayDoseRow = DoseRow & { medication_name: string; medication_dosage: string; };
type InventoryRow = { medication_id: string; profile_id: string; tracking_enabled: number; current_quantity: number; unit: string; consumption_per_taken: number; };
type InventoryEffectRow = { is_applied: number; applied_quantity: number; };
type Db = SQLiteDatabase;
const newId = () => `${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;
function map(row: DoseRow): DoseRecord { return { id: row.id, profileId: row.profile_id, medicationId: row.medication_id, scheduleId: row.schedule_id, scheduledDate: row.scheduled_date, scheduledTime: row.scheduled_time, scheduledAt: row.scheduled_at, status: row.status, takenAt: row.taken_at ?? undefined, statusRecordedAt: row.status_recorded_at ?? undefined, notes: row.notes ?? undefined, medicationName: row.medication_name ?? undefined, medicationDosage: row.medication_dosage ?? undefined, createdAt: row.created_at, updatedAt: row.updated_at }; }
function requireProfile(profileId: string): void { if (!profileId.trim()) throw new Error("Choose a profile before recording doses."); }

export async function createDoseOccurrences(occurrences: CreateDoseOccurrenceInput[]): Promise<void> { if (!occurrences.length) return; await runExclusiveDatabaseTransaction(async (db) => { for (const item of occurrences) { requireProfile(item.profileId); const now = new Date().toISOString(); await db.runAsync(`INSERT OR IGNORE INTO dose_records (id, profile_id, medication_id, schedule_id, scheduled_date, scheduled_time, scheduled_at, status, medication_name, medication_dosage, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, [newId(), item.profileId, item.medicationId, item.scheduleId, item.scheduledDate, item.scheduledTime, `${item.scheduledDate}T${item.scheduledTime}:00`, "pending", item.medicationName, item.medicationDosage, now, now]); } }); }
export async function getTodayDosesByDate(profileId: string, date: string): Promise<TodayDose[]> { requireProfile(profileId); return runDatabaseOperation(async (db) => (await db.getAllAsync<TodayDoseRow>(`SELECT dose_records.*, COALESCE(dose_records.medication_name, medications.name, 'Medication unavailable') AS medication_name, COALESCE(dose_records.medication_dosage, medications.dosage, '') AS medication_dosage FROM dose_records LEFT JOIN medications ON medications.id = dose_records.medication_id WHERE dose_records.profile_id = ? AND dose_records.scheduled_date = ? ORDER BY dose_records.scheduled_time ASC, medication_name COLLATE NOCASE ASC`, [profileId, date])).map((row) => ({ ...map(row), medicationName: row.medication_name, medicationDosage: row.medication_dosage }))); }
export async function getDoseById(profileId: string, id: string): Promise<DoseRecord | null> { requireProfile(profileId); return runDatabaseOperation(async (db) => { const row = await db.getFirstAsync<DoseRow>(`SELECT * FROM dose_records WHERE id=? AND profile_id=?`, [id, profileId]); return row ? map(row) : null; }); }
export async function getPendingDosesByDate(profileId: string, date: string): Promise<DoseRecord[]> { requireProfile(profileId); return runDatabaseOperation(async (db) => (await db.getAllAsync<DoseRow>(`SELECT * FROM dose_records WHERE profile_id=? AND scheduled_date=? AND status='pending' ORDER BY scheduled_time ASC`, [profileId, date])).map(map)); }
export async function deletePendingDosesForScheduleFromLocalDateTime(scheduleId: string, fromDate: string, fromTime: string): Promise<void> { await runDatabaseOperation(async (db) => { await db.runAsync(`DELETE FROM dose_records WHERE schedule_id=? AND status='pending' AND (scheduled_date>? OR (scheduled_date=? AND scheduled_time>=?))`, [scheduleId, fromDate, fromDate, fromTime]); }); }

async function updatePendingStatus(profileId: string, id: string, status: Extract<DoseStatus, "skipped" | "missed">): Promise<void> { requireProfile(profileId); await runExclusiveDatabaseTransaction(async (db) => { const dose = await db.getFirstAsync<Pick<DoseRow, "status">>(`SELECT status FROM dose_records WHERE id=? AND profile_id=?`, [id, profileId]); if (!dose) throw new Error("Dose record not found."); if (!isDoseStatusTransitionAllowed(dose.status, status)) throw new Error("This dose has already been recorded."); const now = new Date().toISOString(); const result = await db.runAsync(`UPDATE dose_records SET status=?, taken_at=NULL, status_recorded_at=?, updated_at=? WHERE id=? AND profile_id=? AND status='pending'`, [status, now, now, id, profileId]); if (result.changes !== 1) throw new Error("This dose was changed before it could be saved. Refresh and try again."); }); }

async function writeInventoryEffect(db: Db, input: { doseId: string; profileId: string; medicationId: string; applied: boolean; quantity: number; now: string }): Promise<void> { await db.runAsync(`INSERT INTO dose_inventory_effects (dose_id, profile_id, medication_id, is_applied, applied_quantity, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT(dose_id) DO UPDATE SET profile_id=excluded.profile_id, medication_id=excluded.medication_id, is_applied=excluded.is_applied, applied_quantity=excluded.applied_quantity, updated_at=excluded.updated_at`, [input.doseId, input.profileId, input.medicationId, input.applied ? 1 : 0, input.quantity, input.now, input.now]); }

async function applyTakenInventoryEffect(db: Db, dose: Pick<DoseRow, "id" | "medication_id">, profileId: string, now: string, eventType: "dose_consumption" | "dose_consumption_reapplied"): Promise<void> { const inventory = await db.getFirstAsync<InventoryRow>(`SELECT medication_id, profile_id, tracking_enabled, current_quantity, unit, consumption_per_taken FROM medication_inventory WHERE medication_id=? AND profile_id=?`, [dose.medication_id, profileId]); if (!inventory || inventory.tracking_enabled !== 1) return; const change = calculateTakenInventoryConsumption(inventory.current_quantity, inventory.consumption_per_taken); await db.runAsync(`INSERT INTO inventory_events (id, profile_id, medication_id, dose_id, event_type, quantity_delta, quantity_before, quantity_after, unit_snapshot, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`, [newId(), profileId, dose.medication_id, dose.id, eventType, change.quantityDelta, change.quantityBefore, change.quantityAfter, inventory.unit, now]); const result = await db.runAsync(`UPDATE medication_inventory SET current_quantity=?, updated_at=? WHERE medication_id=? AND profile_id=? AND tracking_enabled=1`, [change.quantityAfter, now, dose.medication_id, profileId]); if (result.changes !== 1) throw new Error("Refill inventory changed before this dose could be saved. Refresh and try again."); await writeInventoryEffect(db, { doseId: dose.id, profileId, medicationId: dose.medication_id, applied: true, quantity: Math.abs(change.quantityDelta), now }); }

async function reverseTakenInventoryEffect(db: Db, dose: Pick<DoseRow, "id" | "medication_id">, profileId: string, now: string): Promise<void> { const effect = await db.getFirstAsync<InventoryEffectRow>(`SELECT is_applied, applied_quantity FROM dose_inventory_effects WHERE dose_id=? AND profile_id=? AND medication_id=?`, [dose.id, profileId, dose.medication_id]); if (!effect || effect.is_applied !== 1) return; const inventory = await db.getFirstAsync<InventoryRow>(`SELECT medication_id, profile_id, tracking_enabled, current_quantity, unit, consumption_per_taken FROM medication_inventory WHERE medication_id=? AND profile_id=?`, [dose.medication_id, profileId]); if (!inventory || inventory.tracking_enabled !== 1) throw new Error("Refill inventory is unavailable for this correction. Please try again."); const restored = getReversedInventoryQuantity(effect.applied_quantity); const after = inventory.current_quantity + restored; await db.runAsync(`INSERT INTO inventory_events (id, profile_id, medication_id, dose_id, event_type, quantity_delta, quantity_before, quantity_after, unit_snapshot, created_at) VALUES (?, ?, ?, ?, 'dose_consumption_reversal', ?, ?, ?, ?, ?)`, [newId(), profileId, dose.medication_id, dose.id, restored, inventory.current_quantity, after, inventory.unit, now]); const result = await db.runAsync(`UPDATE medication_inventory SET current_quantity=?, updated_at=? WHERE medication_id=? AND profile_id=? AND tracking_enabled=1`, [after, now, dose.medication_id, profileId]); if (result.changes !== 1) throw new Error("Refill inventory changed before this dose could be saved. Refresh and try again."); await writeInventoryEffect(db, { doseId: dose.id, profileId, medicationId: dose.medication_id, applied: false, quantity: 0, now }); }

/** One exclusive transaction owns the Taken transition and its stock effect. */
export async function markDoseTakenInDatabase(profileId: string, id: string, takenAt: string): Promise<void> { requireProfile(profileId); await runExclusiveDatabaseTransaction(async (db) => { const dose = await db.getFirstAsync<Pick<DoseRow, "id" | "status" | "scheduled_date" | "medication_id">>(`SELECT id, status, scheduled_date, medication_id FROM dose_records WHERE id=? AND profile_id=?`, [id, profileId]); if (!dose) throw new Error("Dose record not found."); assertDoseCanBeRecordedOnLocalDate(dose.scheduled_date); if (!isDoseStatusTransitionAllowed(dose.status, "taken")) throw new Error("This dose has already been recorded."); const now = new Date().toISOString(); const result = await db.runAsync(`UPDATE dose_records SET status='taken', taken_at=?, status_recorded_at=?, updated_at=? WHERE id=? AND profile_id=? AND status='pending'`, [takenAt, now, now, id, profileId]); if (result.changes !== 1) throw new Error("This dose was changed before it could be saved. Refresh and try again."); await applyTakenInventoryEffect(db, dose, profileId, now, "dose_consumption"); }); }
export const markDoseSkippedInDatabase = (profileId: string, id: string) => updatePendingStatus(profileId, id, "skipped");
export const markDoseMissedInDatabase = (profileId: string, id: string) => updatePendingStatus(profileId, id, "missed");

/** Corrects only Taken <-> Skipped and keeps dose, stock effect, and audit history together. */
export async function correctDoseStatusInDatabase(profileId: string, id: string, target: DoseStatusCorrectionTarget): Promise<void> { requireProfile(profileId); await runExclusiveDatabaseTransaction(async (db) => { const dose = await db.getFirstAsync<Pick<DoseRow, "id" | "status" | "medication_id">>(`SELECT id, status, medication_id FROM dose_records WHERE id=? AND profile_id=?`, [id, profileId]); if (!dose) throw new Error("Dose record not found."); if (!canCorrectDoseStatus(dose.status, target)) throw new Error("This dose status cannot be changed this way."); const now = new Date().toISOString(); if (target === "skipped") await reverseTakenInventoryEffect(db, dose, profileId, now); const result = await db.runAsync(`UPDATE dose_records SET status=?, taken_at=?, status_recorded_at=?, updated_at=? WHERE id=? AND profile_id=? AND status=?`, [target, target === "taken" ? now : null, now, now, id, profileId, dose.status]); if (result.changes !== 1) throw new Error("This dose was changed before it could be saved. Refresh and try again."); if (target === "taken") await applyTakenInventoryEffect(db, dose, profileId, now, "dose_consumption_reapplied"); }); }
