const spacingScale = {
  xxs: 4,
  xs: 8,
  sm: 12,
  md: 16,
  lg: 20,
  xl: 24,
  xxl: 32,
} as const;

const radiusScale = {
  small: 8,
  medium: 14,
  large: 18,
  pill: 999,
} as const;

const typography = {
  display: { fontSize: 32, lineHeight: 40, fontWeight: "700" },
  pageTitle: { fontSize: 26, lineHeight: 34, fontWeight: "700" },
  sectionTitle: { fontSize: 20, lineHeight: 28, fontWeight: "700" },
  cardTitle: { fontSize: 18, lineHeight: 25, fontWeight: "700" },
  body: { fontSize: 16, lineHeight: 24, fontWeight: "400" },
  bodyStrong: { fontSize: 16, lineHeight: 24, fontWeight: "600" },
  supporting: { fontSize: 14, lineHeight: 21, fontWeight: "400" },
  label: { fontSize: 14, lineHeight: 20, fontWeight: "600", letterSpacing: 0.1 },
  button: { fontSize: 16, lineHeight: 22, fontWeight: "700" },
  caption: { fontSize: 12, lineHeight: 18, fontWeight: "500" },
  numeric: { fontSize: 28, lineHeight: 36, fontWeight: "700", letterSpacing: 0.1 },
} as const;

// Product foundation for signed-in screens and shared primitives. Compatibility
// aliases below keep existing feature screens on the same palette while they
// migrate to the semantic roles.
const lightProductRoles = {
  canvas: "#F8F6F1",
  background: "#F8F6F1",
  backgroundSubtle: "#EEF4F1",
  surface: "#FFFFFF",
  surfaceSubtle: "#EEF4F1",
  elevatedSurface: "#E8F0EC",
  surfaceRaised: "#E8F0EC",
  surfaceMuted: "#EEF4F1",
  primary: "#0A5A54",
  primaryStrong: "#06443F",
  primaryPressed: "#06443F",
  primarySoft: "#DCECE7",
  onPrimary: "#FFFFFF",
  accent: "#E97859",
  accentSoft: "#FBE8E1",
  accentForeground: "#42190F",
  sage: "#789785",
  sageSoft: "#E8EFEA",
  textPrimary: "#18312E",
  textSecondary: "#5E6E69",
  // #899491 is only 3.13:1 on white; use body-safe secondary text contrast.
  textMuted: "#5E6E69",
  border: "#D7E1DD",
  dividerStrong: "#8FA7A0",
  // The supplied #B6CAC2 is too low-contrast for visible control outlines.
  borderStrong: "#718C83",
  strongBorder: "#718C83",
  success: "#357A59",
  successSurface: "#E2F0E7",
  warning: "#A66D20",
  warningSurface: "#F8ECD6",
  danger: "#B34E4A",
  dangerSurface: "#F7E2E0",
  dangerBackground: "#F7E2E0",
  dangerForeground: "#8D3C38",
  placeholder: "#5E6E69",
  inputBackground: "#FFFFFF",
  inputForeground: "#18312E",
  cardBackground: "#FFFFFF",
  cardForeground: "#18312E",
  secondaryBackground: "#DCECE7",
  secondaryForeground: "#06443F",
  selectedBackground: "#0A5A54",
  selectedForeground: "#FFFFFF",
  primaryBackground: "#0A5A54",
  primaryForeground: "#FFFFFF",
  focus: "#0A5A54",
  outlineBorder: "#5F786F",
  outlineForeground: "#0A5A54",
  chipBorder: "#718C83",
  chipBackground: "#FFFFFF",
  chipForeground: "#18312E",
  chipSelectedBackground: "#0A5A54",
  chipSelectedForeground: "#FFFFFF",
  chipPressedBackground: "#DCECE7",
  chipPressedForeground: "#06443F",
  chipSelectedPressedBackground: "#06443F",
  chipSelectedPressedForeground: "#FFFFFF",
  chipDisabledBackground: "#EEF4F1",
  chipDisabledForeground: "#61706C",
  chipDisabledBorder: "#B7C9C1",
  disabledBackground: "#EEF4F1",
  disabledText: "#5E6E69",
  navigationSurface: "#FFFFFF",
  navigationSelected: "#DCECE7",
  navigationSelectedText: "#06443F",
  navigationInactive: "#61706C",
  navigationBorder: "#D7E1DD",
  // Backward-compatible feature aliases now resolve to the product palette.
  surfaceElevated: "#E8F0EC",
  card: "#FFFFFF",
  text: "#18312E",
  muted: "#61706C",
};

const darkProductRoles = {
  canvas: "#101C19",
  background: "#101C19",
  backgroundSubtle: "#1D302B",
  surface: "#172723",
  surfaceSubtle: "#1D302B",
  elevatedSurface: "#233932",
  surfaceRaised: "#233932",
  surfaceMuted: "#1D302B",
  primary: "#88C7B8",
  primaryStrong: "#A8D8CC",
  primaryPressed: "#A8D8CC",
  primarySoft: "#23463E",
  onPrimary: "#101C19",
  accent: "#F39478",
  accentSoft: "#4A2B24",
  accentForeground: "#482219",
  sage: "#A4BCAA",
  sageSoft: "#263B33",
  textPrimary: "#F4F6F4",
  textSecondary: "#B7C4BF",
  textMuted: "#9BB3AA",
  border: "#304A43",
  dividerStrong: "#71877F",
  // #45665D is below 3:1 against the raised surface; this keeps control edges visible.
  borderStrong: "#6A8980",
  strongBorder: "#6A8980",
  success: "#83C49C",
  successSurface: "#203D2E",
  warning: "#E1B76D",
  warningSurface: "#49391E",
  danger: "#EB8E88",
  dangerSurface: "#4D2928",
  dangerBackground: "#4D2928",
  dangerForeground: "#EB8E88",
  placeholder: "#B7C4BF",
  inputBackground: "#172723",
  inputForeground: "#F4F6F4",
  cardBackground: "#172723",
  cardForeground: "#F4F6F4",
  secondaryBackground: "#23463E",
  secondaryForeground: "#A8D8CC",
  selectedBackground: "#88C7B8",
  selectedForeground: "#101C19",
  primaryBackground: "#88C7B8",
  primaryForeground: "#101C19",
  focus: "#A8D8CC",
  outlineBorder: "#9BB3AA",
  outlineForeground: "#A8D8CC",
  chipBorder: "#6A8980",
  chipBackground: "#172723",
  chipForeground: "#F4F6F4",
  chipSelectedBackground: "#88C7B8",
  chipSelectedForeground: "#101C19",
  chipPressedBackground: "#23463E",
  chipPressedForeground: "#F4F6F4",
  chipSelectedPressedBackground: "#A8D8CC",
  chipSelectedPressedForeground: "#101C19",
  chipDisabledBackground: "#1D302B",
  chipDisabledForeground: "#899B95",
  chipDisabledBorder: "#45665D",
  disabledBackground: "#1D302B",
  disabledText: "#899B95",
  navigationSurface: "#233932",
  navigationSelected: "#23463E",
  navigationSelectedText: "#A8D8CC",
  navigationInactive: "#B7C4BF",
  navigationBorder: "#304A43",
  surfaceElevated: "#233932",
  card: "#172723",
  text: "#F4F6F4",
  muted: "#B7C4BF",
};

const legacyUiColors = {
    // Brand palette: deep teal leads; coral and sage support rather than compete.
    background: "#FBF4E9",
    backgroundSubtle: "#F3EBDD",
    surface: "#FFFDF9",
    surfaceRaised: "#FFFFFF",
    surfaceMuted: "#F1EBDD",
    primary: "#024A47",
    primaryPressed: "#013936",
    onPrimary: "#FFFFFF",
    accent: "#FC6B44",
    accentForeground: "#42190F",
    support: "#658A63",
    textPrimary: "#193B38",
    textSecondary: "#405B56",
    textMuted: "#526B65",
    textInverse: "#FFFFFF",
    border: "#D7DED4",
    borderStrong: "#9EB2A9",
    divider: "#E6E2D8",
    focus: "#024A47",
    scrim: "#17322F",
    success: "#2F6746",
    warning: "#785500",
    danger: "#9B3531",
    pending: "#285D68",
    taken: "#2F6746",
    skipped: "#785500",
    missed: "#9B3531",
    lowStock: "#92501E",
    placeholder: "#526B65",
    disabledBackground: "#E8E7DF",
    disabledText: "#56625D",
    inputBackground: "#FFFFFF",
    inputForeground: "#193B38",
    secondaryBackground: "#E3EEE9",
    secondaryForeground: "#15534D",
    selectedBackground: "#024A47",
    selectedForeground: "#FFFFFF",
    cardBackground: "#FFFFFF",
    cardForeground: "#193B38",
    dangerBackground: "#F7E5E1",
    dangerForeground: "#852B29",
    successSurface: "#E5F0E6",
    warningSurface: "#F4ECD5",
    dangerSurface: "#F7E5E1",
    pendingSurface: "#E3EEEB",
    badgeTakenBackground: "#E5F0E6",
    badgeTakenForeground: "#28563C",
    badgeSkippedBackground: "#F4ECD5",
    badgeSkippedForeground: "#634600",
    badgeMissedBackground: "#F7E5E1",
    badgeMissedForeground: "#852B29",
    badgePendingBackground: "#E3EEEB",
    badgePendingForeground: "#20555D",
    badgeUpcomingBackground: "#EAECE6",
    badgeUpcomingForeground: "#46574E",
    badgeActiveBackground: "#E5F0E6",
    badgeActiveForeground: "#28563C",
    badgePausedBackground: "#F4ECD5",
    badgePausedForeground: "#634600",
    badgeExpiredBackground: "#F7E5E1",
    badgeExpiredForeground: "#852B29",
    chipBackground: "#FFFFFF",
    chipForeground: "#193B38",
    chipSelectedBackground: "#024A47",
    chipSelectedForeground: "#FFFFFF",
    chipPressedBackground: "#E3EEE9",
    chipPressedForeground: "#15534D",
    chipSelectedPressedBackground: "#013936",
    chipSelectedPressedForeground: "#FFFFFF",
    chipDisabledBackground: "#E8E7DF",
    chipDisabledForeground: "#56625D",
    chipBorder: "#66827B",
    chipDisabledBorder: "#9EB2A9",
    outlineBorder: "#66827B",
    outlineForeground: "#024A47",
    // Legacy color aliases retained while older screens migrate to semantic names.
    surfaceElevated: "#FFFFFF",
    card: "#FFFFFF",
    text: "#193B38",
    muted: "#405B56",
    primaryBackground: "#024A47",
    primaryForeground: "#FFFFFF",
};

export const ui = {
  colors: { ...legacyUiColors, ...lightProductRoles },
  typography,
  spacing: {
    ...spacingScale,
    screen: spacingScale.md,
    section: spacingScale.xl,
    card: spacingScale.md,
    compact: spacingScale.xs,
  },
  radius: {
    ...radiusScale,
    card: radiusScale.large,
    button: radiusScale.medium,
    chip: radiusScale.pill,
  },
  elevation: { card: 0, raised: 1, overlay: 4 },
  touch: { minimum: 48 },
} as const;

export type AppearancePreference = "system" | "light" | "dark";
export type AppColorTokens = { [Key in keyof typeof ui.colors]: string };
export type UiThemeTokens = Omit<typeof ui, "colors"> & { colors: AppColorTokens };

export type ButtonColorState = "default" | "pressed" | "disabled";
type ButtonColorTone = "primary" | "secondary" | "outline" | "danger";
type ButtonColorRoles = {
  background: keyof AppColorTokens;
  foreground: keyof AppColorTokens;
  border: keyof AppColorTokens;
};

const buttonColorRoles: Record<ButtonColorTone, Record<Exclude<ButtonColorState, "disabled">, ButtonColorRoles>> = {
  primary: {
    default: { background: "primary", foreground: "onPrimary", border: "primary" },
    pressed: { background: "primaryPressed", foreground: "onPrimary", border: "primaryPressed" },
  },
  secondary: {
    default: { background: "secondaryBackground", foreground: "secondaryForeground", border: "outlineBorder" },
    pressed: { background: "surfaceMuted", foreground: "secondaryForeground", border: "outlineBorder" },
  },
  outline: {
    default: { background: "inputBackground", foreground: "outlineForeground", border: "outlineBorder" },
    pressed: { background: "secondaryBackground", foreground: "secondaryForeground", border: "outlineBorder" },
  },
  danger: {
    default: { background: "dangerBackground", foreground: "dangerForeground", border: "danger" },
    pressed: { background: "dangerSurface", foreground: "dangerForeground", border: "danger" },
  },
};

/** A single source of truth for readable button colors in every theme/state. */
export function getButtonColorRoles(tone: ButtonColorTone, state: ButtonColorState = "default"): ButtonColorRoles {
  if (state === "disabled") {
    return { background: "disabledBackground", foreground: "disabledText", border: "disabledText" };
  }
  return buttonColorRoles[tone][state];
}

const legacyDarkUiColors = {
  ...ui.colors,
  background: "#14211E",
  backgroundSubtle: "#192925",
  surface: "#1D2E29",
  surfaceRaised: "#243630",
  surfaceMuted: "#2A3C35",
  primary: "#70B5A7",
  primaryPressed: "#8AC8BB",
  onPrimary: "#082C27",
  accent: "#FF9877",
  accentForeground: "#482219",
  support: "#A1C398",
  textPrimary: "#F1F2E9",
  textSecondary: "#CBD8D0",
  textMuted: "#ADC0B5",
  textInverse: "#10221E",
  border: "#40574E",
  borderStrong: "#70877C",
  divider: "#33483F",
  focus: "#8AC8BB",
  scrim: "#07110F",
  success: "#9DD6AE",
  warning: "#F1CC79",
  danger: "#FFB3A9",
  pending: "#A9D9D1",
  taken: "#9DD6AE",
  skipped: "#F1CC79",
  missed: "#FFB3A9",
  lowStock: "#F0B17A",
  placeholder: "#ADC0B5",
  disabledBackground: "#30423A",
  disabledText: "#A8B7AF",
  inputBackground: "#192723",
  inputForeground: "#F1F2E9",
  secondaryBackground: "#29413A",
  secondaryForeground: "#C4E2D8",
  selectedBackground: "#70B5A7",
  selectedForeground: "#082C27",
  cardBackground: "#1D2E29",
  cardForeground: "#F1F2E9",
  dangerBackground: "#482A27",
  dangerForeground: "#FFD1C9",
  successSurface: "#244033",
  warningSurface: "#47391F",
  dangerSurface: "#482A27",
  pendingSurface: "#243C39",
  badgeTakenBackground: "#244033",
  badgeTakenForeground: "#BDE9C7",
  badgeSkippedBackground: "#47391F",
  badgeSkippedForeground: "#FFE2A1",
  badgeMissedBackground: "#482A27",
  badgeMissedForeground: "#FFD1C9",
  badgePendingBackground: "#243C39",
  badgePendingForeground: "#BFE4DE",
  badgeUpcomingBackground: "#314139",
  badgeUpcomingForeground: "#D6E0D8",
  badgeActiveBackground: "#244033",
  badgeActiveForeground: "#BDE9C7",
  badgePausedBackground: "#47391F",
  badgePausedForeground: "#FFE2A1",
  badgeExpiredBackground: "#482A27",
  badgeExpiredForeground: "#FFD1C9",
  chipBackground: "#192723",
  chipForeground: "#F1F2E9",
  chipSelectedBackground: "#70B5A7",
  chipSelectedForeground: "#082C27",
  chipPressedBackground: "#31463E",
  chipPressedForeground: "#F1F2E9",
  chipSelectedPressedBackground: "#8AC8BB",
  chipSelectedPressedForeground: "#082C27",
  chipDisabledBackground: "#30423A",
  chipDisabledForeground: "#A8B7AF",
  chipBorder: "#61766D",
  chipDisabledBorder: "#52665D",
  outlineBorder: "#839A8F",
  outlineForeground: "#9FD1C6",
  surfaceElevated: "#243630",
  card: "#1D2E29",
  text: "#F1F2E9",
  muted: "#CBD8D0",
  primaryBackground: "#70B5A7",
  primaryForeground: "#082C27",
};

export const darkUiColors: AppColorTokens = { ...legacyDarkUiColors, ...darkProductRoles };

function profileSetupAlias(colors: AppColorTokens) {
  return {
    canvas: colors.canvas,
    surface: colors.surface,
    surfaceSubtle: colors.surfaceSubtle,
    surfaceMint: colors.primarySoft,
    surfaceElevated: colors.elevatedSurface,
    primary: colors.primary,
    primaryStrong: colors.primaryStrong,
    primarySoft: colors.primarySoft,
    onPrimary: colors.onPrimary,
    accent: colors.accent,
    accentSoft: colors.accentSoft,
    sage: colors.sage,
    sageSoft: colors.sageSoft,
    textPrimary: colors.textPrimary,
    textSecondary: colors.textSecondary,
    textMuted: colors.textMuted,
    border: colors.border,
    borderStrong: colors.strongBorder,
    success: colors.success,
    successSurface: colors.successSurface,
    warning: colors.warning,
    warningSurface: colors.warningSurface,
    danger: colors.danger,
    dangerSurface: colors.dangerSurface,
    // Backward-compatible field names for the existing Auth/KYC components.
    surfaceMuted: colors.surfaceSubtle,
    text: colors.textPrimary,
    teal: colors.primary,
    tealPressed: colors.primaryStrong,
    onTeal: colors.onPrimary,
    mint: colors.primarySoft,
    coral: colors.accent,
    amber: colors.warning,
    error: colors.danger,
    errorSurface: colors.dangerSurface,
  };
}

/** Auth/KYC compatibility view over the same authoritative product palettes. */
export const profileSetupColors = {
  light: profileSetupAlias(ui.colors),
  dark: profileSetupAlias(darkUiColors),
};

export function resolveAppearance(preference: AppearancePreference, systemScheme: "light" | "dark" | "unspecified" | null | undefined): "light" | "dark" {
  return preference === "system" ? (systemScheme === "dark" ? "dark" : "light") : preference;
}

function channelToLinear(channel: number): number {
  const normalized = channel / 255;
  return normalized <= 0.04045 ? normalized / 12.92 : ((normalized + 0.055) / 1.055) ** 2.4;
}

/** Relative-luminance contrast ratio for six-digit hexadecimal UI colors. */
export function getColorContrastRatio(background: string, foreground: string): number {
  const luminance = (value: string) => {
    const hex = value.replace("#", "");
    if (!/^[0-9A-Fa-f]{6}$/.test(hex)) throw new Error(`Expected a six-digit hex color, received ${value}.`);
    const [red, green, blue] = [0, 2, 4].map((offset) => channelToLinear(Number.parseInt(hex.slice(offset, offset + 2), 16)));
    return red * 0.2126 + green * 0.7152 + blue * 0.0722;
  };
  const first = luminance(background);
  const second = luminance(foreground);
  return (Math.max(first, second) + 0.05) / (Math.min(first, second) + 0.05);
}
