import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, SectionList, StyleSheet, Text, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { addDaysToLocalDate, toLocalDateString } from "@/features/doses/dose.domain";
import { groupHistoryByLocalDate } from "@/features/history/history.service";
import { HistoryDose, HistoryStatusFilter } from "@/features/history/history.types";
import { useHistory } from "@/hooks/useHistory";
import { useMedications } from "@/hooks/useMedications";
import { AppColorTokens, ui } from "@/components/ui-tokens";
import { useAppTheme } from "@/components/app-theme-provider";
import { ScreenHeader } from "@/components/screen-header";
import { StatusBadge, ThemedChip } from "@/components/themed-ui";
import { AccordionSection, createHistoryAccordionSections, resetExpandedHistoryDate, toggleExpandedHistoryDate } from "@/features/history/history-accordion.domain";
import { useProfileStore } from "@/state/profile.store";

const statuses: HistoryStatusFilter[] = ["all", "taken", "skipped", "missed"];
const ranges = ["all", "today", "week"] as const;
function displayTime(value: string) { const [hours, minutes] = value.split(":").map(Number); return new Date(2000, 0, 1, hours, minutes).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" }); }

export default function HistoryScreen() {
  const { colors } = useAppTheme();
  const styles = createStyles(colors);
  const selectedProfileId = useProfileStore((state) => state.selectedProfileId);
  const { doses, isLoading, deletingDoseId, error, loadHistory, deleteHistoryRecord, clearError } = useHistory();
  const { medications, loadMedications } = useMedications();
  const [status, setStatus] = useState<HistoryStatusFilter>("all"); const [range, setRange] = useState<(typeof ranges)[number]>("all"); const [medicationId, setMedicationId] = useState<string>(); const [expandedDate, setExpandedDate] = useState<string | null>(null);
  const query = useMemo(() => ({ status, medicationId, ...(range === "today" ? { fromDate: toLocalDateString(), toDate: toLocalDateString() } : range === "week" ? { fromDate: addDaysToLocalDate(toLocalDateString(), -6), toDate: toLocalDateString() } : {}) }), [status, medicationId, range]);
  const refresh = useCallback(() => void loadHistory(query), [loadHistory, query]);
  useFocusEffect(useCallback(() => { refresh(); return () => { setExpandedDate(resetExpandedHistoryDate()); }; }, [refresh, selectedProfileId]));
  useEffect(() => { void loadMedications("all"); }, [loadMedications, selectedProfileId]);
  const groups = useMemo(() => groupHistoryByLocalDate(doses), [doses]);
  const sections = useMemo(() => createHistoryAccordionSections(groups, expandedDate), [expandedDate, groups]);
  const resetAccordion = () => { setExpandedDate(resetExpandedHistoryDate()); };
  const changeStatus = (value: HistoryStatusFilter) => { resetAccordion(); setStatus(value); };
  const changeRange = (value: (typeof ranges)[number]) => { resetAccordion(); setRange(value); };
  const changeMedication = (value?: string) => { resetAccordion(); setMedicationId(value); };
  const confirmDelete = (dose: HistoryDose) => Alert.alert("Delete history record?", "This will permanently remove this intake record from your history. This action cannot be undone.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void deleteHistoryRecord(dose).catch(() => undefined) }]);
  return <View style={styles.container}><SectionList<HistoryDose, AccordionSection<HistoryDose>> sections={sections} keyExtractor={(item) => item.id} refreshing={isLoading} onRefresh={refresh} contentContainerStyle={styles.list} stickySectionHeadersEnabled={false} renderSectionHeader={({ section }) => <DateHeader group={section} expanded={expandedDate === section.date} onPress={() => setExpandedDate((value) => toggleExpandedHistoryDate(value, section.date))} />} renderItem={({ item }) => <HistoryCard dose={item} deleting={deletingDoseId === item.id} onDelete={confirmDelete} />} ListHeaderComponent={<><ScreenHeader title="History" /><Text style={styles.subtitle}>Your saved medication records</Text><Text style={styles.filterLabel}>Status</Text><View style={styles.chips}>{statuses.map((value) => <FilterChip key={value} selected={status === value} label={value === "all" ? "All" : value[0].toUpperCase() + value.slice(1)} onPress={() => changeStatus(value)} />)}</View><Text style={styles.filterLabel}>Date</Text><View style={styles.chips}>{ranges.map((value) => <FilterChip key={value} selected={range === value} label={value === "all" ? "All dates" : value === "today" ? "Today" : "Last 7 days"} onPress={() => changeRange(value)} />)}</View><Text style={styles.filterLabel}>Medication</Text><View style={styles.chips}><FilterChip selected={!medicationId} label="All medicines" onPress={() => changeMedication()} />{medications.slice(0, 6).map((medication) => <FilterChip key={medication.id} selected={medicationId === medication.id} label={medication.name} onPress={() => changeMedication(medication.id)} />)}</View>{error ? <Pressable onPress={clearError} style={styles.error}><Text style={styles.errorText}>{error}</Text><Text>Tap to dismiss</Text></Pressable> : null}{isLoading && !doses.length ? <ActivityIndicator size="large" style={styles.loader} /> : null}</>} ListEmptyComponent={!isLoading ? <View style={styles.empty}><Text style={styles.name}>No dose history yet.</Text><Text style={styles.subtitle}>Recorded doses will appear here.</Text></View> : null} /></View>;
}

function DateHeader({ group, expanded, onPress }: { group: AccordionSection<HistoryDose> & { label: string }; expanded: boolean; onPress: () => void }) { const { colors } = useAppTheme(); const styles = createStyles(colors); const action = expanded ? "Collapse" : "Open"; const count = group.recordCount; return <Pressable accessibilityRole="button" accessibilityLabel={`${action} history for ${group.label}, ${count} medication record${count === 1 ? "" : "s"}, ${expanded ? "expanded" : "collapsed"}`} accessibilityState={{ expanded }} onPress={onPress} style={styles.dateHeader}><View style={styles.dateCopy}><Text style={styles.dateHeading}>{group.label}</Text><Text style={styles.count}>{count} record{count === 1 ? "" : "s"}</Text></View><Text accessibilityElementsHidden style={styles.chevron}>{expanded ? "▲" : "▼"}</Text></Pressable>; }
function FilterChip({ selected, label, onPress }: { selected: boolean; label: string; onPress: () => void }) { return <ThemedChip label={label} selected={selected} onPress={onPress} accessibilityLabel={`${label}${selected ? ", selected" : ""}`} />; }
function HistoryCard({ dose, deleting, onDelete }: { dose: HistoryDose; deleting: boolean; onDelete: (dose: HistoryDose) => void }) { const { colors } = useAppTheme(); const styles = createStyles(colors); return <View style={styles.card} accessible accessibilityLabel={`${dose.medicationName}, ${dose.medicationDosage}, scheduled ${dose.scheduledDate} at ${displayTime(dose.scheduledTime)}, ${dose.status}`}><View style={styles.cardHeader}><View style={styles.cardText}><Text style={styles.name}>{dose.medicationName}</Text><Text style={styles.dosage}>{dose.medicationDosage}</Text></View><StatusBadge label={dose.status[0].toUpperCase() + dose.status.slice(1)} tone={dose.status} /></View><Text style={styles.detail}>Scheduled {displayTime(dose.scheduledTime)}</Text>{dose.status === "taken" && dose.takenAt ? <Text style={styles.detail}>Recorded {new Date(dose.takenAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</Text> : null}<View style={styles.cardActions}><Pressable accessibilityRole="button" accessibilityLabel={`View details for ${dose.medicationName} at ${displayTime(dose.scheduledTime)}`} onPress={() => router.push({ pathname: "/dose-detail" as never, params: { id: dose.id } } as never)} style={styles.textButton}><Text style={styles.textButtonLabel}>Details</Text></Pressable>{dose.status !== "pending" ? <Pressable accessibilityRole="button" accessibilityLabel={`Delete history record for ${dose.medicationName} at ${displayTime(dose.scheduledTime)}`} accessibilityState={{ disabled: deleting, busy: deleting }} disabled={deleting} onPress={() => onDelete(dose)} style={styles.deleteButton}><Text style={styles.deleteLabel}>{deleting ? "Deleting..." : "Delete"}</Text></Pressable> : null}</View></View>; }

const createStyles = (colors: AppColorTokens) => StyleSheet.create({ container:{flex:1,backgroundColor:colors.background},list:{padding:ui.spacing.screen,paddingTop:20,paddingBottom:120},subtitle:{marginTop:18,fontSize:16,lineHeight:22,color:colors.muted},filterLabel:{marginTop:ui.spacing.section,fontSize:15,fontWeight:"700",color:colors.textPrimary},chips:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:9},error:{marginTop:16,padding:14,borderRadius:ui.radius.button,backgroundColor:colors.dangerBackground},errorText:{fontWeight:"700",color:colors.dangerForeground},loader:{marginVertical:32},dateHeader:{minHeight:68,flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:18,marginBottom:8,padding:14,borderWidth:1,borderColor:colors.border,borderRadius:ui.radius.card,backgroundColor:colors.cardBackground},dateCopy:{flex:1,flexShrink:1},dateHeading:{fontSize:18,fontWeight:"700",color:colors.cardForeground},count:{marginTop:3,fontSize:14,color:colors.textMuted},chevron:{marginLeft:12,fontSize:16,fontWeight:"700",color:colors.primary},card:{padding:ui.spacing.card,borderRadius:ui.radius.card,borderWidth:1,borderColor:colors.border,borderTopColor:colors.borderStrong,backgroundColor:colors.cardBackground,marginBottom:12},cardHeader:{flexDirection:"row",alignItems:"flex-start",justifyContent:"space-between",gap:12},cardText:{flex:1,flexShrink:1},name:{fontSize:18,fontWeight:"700",color:colors.cardForeground,flexShrink:1},dosage:{marginTop:3,fontSize:16,color:colors.textSecondary},detail:{marginTop:10,fontSize:15,color:colors.textMuted},cardActions:{flexDirection:"row",gap:16,marginTop:14,alignItems:"center"},textButton:{minHeight:ui.touch.minimum,justifyContent:"center",paddingHorizontal:4},textButtonLabel:{fontWeight:"700",color:colors.outlineForeground},deleteButton:{minHeight:ui.touch.minimum,justifyContent:"center",paddingHorizontal:6},deleteLabel:{fontWeight:"700",color:colors.dangerForeground},empty:{alignItems:"center",paddingVertical:48,gap:8} });
