import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Alert, FlatList, Pressable, StyleSheet, Text, TextInput, View } from "react-native";
import { router, useFocusEffect } from "expo-router";
import { ScreenHeader } from "@/components/screen-header";
import { AppColorTokens, ui } from "@/components/ui-tokens";
import { useAppTheme } from "@/components/app-theme-provider";
import { useMedications } from "@/hooks/useMedications";
import { Medication } from "@/features/medications/medication.types";
import { hasMedicationChanges } from "@/features/medications/medication.domain";
import { AutoDismissNotice } from "@/components/auto-dismiss-notice";
import { StatusBadge, ThemedButton, ThemedChip } from "@/components/themed-ui";
import { useProfileStore } from "@/state/profile.store";

type Filter = "active" | "paused" | "archived";
type Editing = Pick<Medication, "id" | "name" | "dosage">;

export default function MedicationsScreen() {
  const { colors } = useAppTheme();
  const styles = createStyles(colors);
  const store = useMedications();
  const selectedProfileId = useProfileStore((state) => state.selectedProfileId);
  const [name, setName] = useState(""); const [dosage, setDosage] = useState("");
  const [filter, setFilter] = useState<Filter>("active"); const [editing, setEditing] = useState<Editing | null>(null);
  const [isSaving, setIsSaving] = useState(false); const [notice, setNotice] = useState<string | null>(null);
  useFocusEffect(useCallback(() => () => setNotice(null), []));
  useEffect(() => { void store.loadMedications(filter); }, [filter, selectedProfileId, store.loadMedications]);
  const changed = useMemo(() => Boolean(editing && hasMedicationChanges(editing as Medication, { name, dosage })), [name, dosage, editing]);
  const cancelEdit = () => { setEditing(null); setName(""); setDosage(""); };
  const beginEdit = (m: Medication) => { setEditing({ id: m.id, name: m.name, dosage: m.dosage }); setName(m.name); setDosage(m.dosage); setNotice(null); };
  async function save() { setIsSaving(true); try { if (editing) { await store.updateMedication(editing.id, { name, dosage }); setNotice("Medication updated."); } else { await store.createMedication({ name, dosage }); setNotice("Medication added."); } cancelEdit(); } catch {} finally { setIsSaving(false); } }
  function requestSave() { if (editing && !changed) return; if (!editing) { void save(); return; } Alert.alert("Save medication changes?", `You are updating:\n\n${editing.name}`, [{ text: "Cancel", style: "cancel" }, { text: "Update", onPress: () => void save() }]); }
  function requestArchive(m: Medication) { Alert.alert("Archive medication?", `${m.name} will move to Archived. Existing dose history will be kept.`, [{ text: "Cancel", style: "cancel" }, { text: "Archive", onPress: () => void store.archiveMedication(m.id).then(() => setNotice("Medication archived.")).catch(() => undefined) }]); }
  function requestDelete(m: Medication) { Alert.alert("Delete medication?", `“${m.name}” will be removed from your medication list. Future schedules and reminders for this medication will be cancelled. Existing finalized intake history will be preserved.`, [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void store.deleteMedication(m.id).then(() => setNotice("Medication deleted.")).catch(() => undefined) }]); }
  function more(m: Medication) { Alert.alert(m.name, "Choose a medication action.", [{ text: "Archive", onPress: () => requestArchive(m) }, { text: "Delete medication", style: "destructive", onPress: () => requestDelete(m) }, { text: "Cancel", style: "cancel" }]); }
  const empty = filter === "active" ? "No active medications." : filter === "paused" ? "No paused medications." : "No archived medications.";
  return <View style={styles.container}><FlatList data={store.medications} keyExtractor={(x) => x.id} contentContainerStyle={styles.list} keyboardShouldPersistTaps="handled" renderItem={({ item }) => <Card medication={item} onEdit={beginEdit} onMore={more} onRestore={(id) => void store.restoreMedication(id).then(() => setNotice("Medication restored.")).catch(() => undefined)} />} ListHeaderComponent={<>
    <ScreenHeader title="Medications" />
    <Text style={styles.intro}>Add and manage your medications</Text>
    <View style={styles.filters}>{(["active", "paused", "archived"] as const).map((v) => <ThemedChip key={v} label={v[0].toUpperCase() + v.slice(1)} selected={filter === v} onPress={() => setFilter(v)} accessibilityLabel={`${v} medications${filter === v ? ", selected" : ""}`} />)}</View>
    {store.error ? <Pressable onPress={store.clearError} style={styles.error}><Text style={styles.messageText}>{store.error}</Text><Text>Tap to dismiss</Text></Pressable> : null}<AutoDismissNotice message={notice} onDismiss={() => setNotice(null)} />
    <View style={styles.form}><Text style={styles.formTitle}>{editing ? "Edit Medication" : "Add medication"}</Text>{editing ? <Text style={styles.editing}>Editing: {editing.name}</Text> : null}<TextInput accessibilityLabel="Medication name" placeholder="Medication name" placeholderTextColor={colors.muted} value={name} onChangeText={setName} style={styles.input} /><TextInput accessibilityLabel="Dosage" placeholder="Dosage, for example 500 mg" placeholderTextColor={colors.muted} value={dosage} onChangeText={setDosage} style={styles.input} />{editing && !changed ? <Text style={styles.noChanges}>No changes to save.</Text> : null}<View style={styles.formActions}>{editing ? <Button label="Cancel" onPress={cancelEdit} disabled={isSaving} secondary accessibilityLabel="Cancel editing" /> : null}<Button label={isSaving ? "Saving..." : editing ? "Update Medication" : "Add Medication"} onPress={requestSave} disabled={isSaving || Boolean(editing && !changed)} accessibilityLabel={editing ? "Update medication" : "Add medication"} /></View></View>
    <Text style={styles.heading}>{filter[0].toUpperCase() + filter.slice(1)} medications</Text>{store.isLoading && !store.medications.length ? <ActivityIndicator size="large" style={styles.loader} /> : null}
  </>} ListEmptyComponent={!store.isLoading ? <View style={styles.empty}><Text style={styles.emptyTitle}>{empty}</Text><Text style={styles.emptyText}>{filter === "active" ? "Add your first medication above." : "Choose another medication group to review it."}</Text></View> : null} /></View>;
}

function Button({ label, onPress, disabled, secondary, accessibilityLabel }: { label: string; onPress: () => void; disabled?: boolean; secondary?: boolean; accessibilityLabel: string }) { return <ThemedButton label={label} onPress={onPress} disabled={disabled} tone={secondary ? "outline" : "primary"} accessibilityLabel={accessibilityLabel} style={secondary ? undefined : { flexGrow: 1 }} />; }
function Card({ medication, onEdit, onMore, onRestore }: { medication: Medication; onEdit: (m: Medication) => void; onMore: (m: Medication) => void; onRestore: (id: string) => void }) { const { colors } = useAppTheme(); const styles = createStyles(colors); const status = medication.archivedAt ? "Archived" : medication.isActive ? "Active" : "Paused"; const tone = medication.archivedAt ? "expired" : medication.isActive ? "active" : "paused"; return <View style={styles.card} accessible accessibilityLabel={`${medication.name}, ${medication.dosage}, ${status}`}><Text style={styles.name}>{medication.name}</Text><Text style={styles.dosage}>{medication.dosage}</Text><StatusBadge label={status} tone={tone} style={styles.status} /><View style={styles.actions}>{medication.archivedAt ? <Button label="Restore" onPress={() => onRestore(medication.id)} accessibilityLabel={`Restore ${medication.name}`} secondary /> : <><Button label="Schedule" onPress={() => router.push({ pathname: "/schedule", params: { medicationId: medication.id, medicationName: medication.name } })} accessibilityLabel={`Manage schedule for ${medication.name}`} secondary /><Button label="Edit" onPress={() => onEdit(medication)} accessibilityLabel={`Edit ${medication.name}`} secondary /><Button label="More" onPress={() => onMore(medication)} accessibilityLabel={`More actions for ${medication.name}`} secondary /></>}</View></View>; }

const createStyles = (colors: AppColorTokens) => StyleSheet.create({ container:{flex:1,backgroundColor:colors.background},list:{padding:ui.spacing.screen,paddingTop:20,paddingBottom:120},intro:{marginTop:18,fontSize:16,lineHeight:22,color:colors.textSecondary},filters:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:16},form:{gap:12,marginTop:ui.spacing.section,padding:ui.spacing.card,borderWidth:1,borderColor:colors.border,borderRadius:ui.radius.card,backgroundColor:colors.cardBackground},formTitle:{fontSize:18,fontWeight:"700",color:colors.cardForeground},editing:{fontSize:15,fontWeight:"600",color:colors.primary},input:{minHeight:52,borderWidth:1,borderColor:colors.outlineBorder,borderRadius:ui.radius.button,paddingHorizontal:14,fontSize:16,color:colors.inputForeground,backgroundColor:colors.inputBackground},formActions:{flexDirection:"row",flexWrap:"wrap",gap:10},noChanges:{color:colors.textMuted,fontSize:14},heading:{marginTop:ui.spacing.section,marginBottom:12,fontSize:19,fontWeight:"700",color:colors.textPrimary},card:{padding:ui.spacing.card,marginBottom:12,borderWidth:1,borderColor:colors.border,borderTopColor:colors.borderStrong,borderRadius:ui.radius.card,backgroundColor:colors.cardBackground},name:{fontSize:19,fontWeight:"700",color:colors.cardForeground,flexShrink:1},dosage:{marginTop:4,fontSize:16,color:colors.textSecondary},status:{marginTop:12},actions:{flexDirection:"row",flexWrap:"wrap",gap:8,marginTop:14},empty:{paddingVertical:36,alignItems:"center"},emptyTitle:{fontSize:18,fontWeight:"700",color:colors.textPrimary},emptyText:{marginTop:7,textAlign:"center",color:colors.textSecondary},loader:{marginVertical:26},error:{marginTop:16,padding:14,borderRadius:ui.radius.button,backgroundColor:colors.dangerBackground},success:{marginTop:16,padding:14,borderRadius:ui.radius.button,backgroundColor:colors.successSurface},messageText:{fontWeight:"700",color:colors.textPrimary} });
